services:
  mongodb:
    image: mongo:8
    container_name: netflix_mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
  redis:
    image: redis:8-alpine
    container_name: netflix_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  redis_commander:
    image: rediscommander/redis-commander:latest
    container_name: netflix_redis_commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis

volumes:
  mongodb_data:
  redis_data:

